<?php

/**
 * Implements hook_help()
 */
function user_warn($path, $arg) {
  if ($path == 'admin/help#user_warn') {
    return t('User Warn allows administrators to send a standard e-mail to site user to notify them of improper behavior');
  }
}

function user_warn_menu() {
  $items = array();

  $items['admin/config/people/user_warn'] = array(
    'title' => 'User Warn',
    'description' => 'Configuration for the user warn module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_warn_form'),
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['user/%/warn'] = array(
    'title' => 'Warn',
    'description' => 'Send a user an email about improper site behavior',
    'page callback' => drupal_get_form,
    'page arguments' => array('user_warn_confirm_form', 1),
    'access arguments' => array('administer users'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function user_warn_form($form, &$form_state) {
  $form['user_warn_default_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Warning e-mail subject'),
    '#description' => t('The subject of the e-mail which will be sent to users'),
    '#size' => 40,
    '#maxlength' => 120,
    '#required' => TRUE,
    '#default_value' => variable_get('user_warn_default_subject', 'Administrative Warning'),
  );

  define('USER_WARN_MAIL_TEXT', 
      'Hello [user:name], We have been notified that you have posted comments on our [site:name] that are in violation of our terms of service.  If this behavior continues your account will be suspended.
    
   Sincerely,
   [site:name] administrative staff');
  
  $form['user_warn_e-mail_text'] = array(
    '#type' => 'textarea',
    '#rows' => 10,
    '#columns' => 40,
    '#title' => t('Warning e-mail text'),
    '#required' => TRUE,
    '#description' => t('The text of the e-mail'),
    '#default_value' => variable_get('user_warn_e-mail_text', USER_WARN_MAIL_TEXT),
  );

  $form['user_warn_e-mail_bcc'] = array(
    '#type' => 'checkbox',
    '#title' => t('BCC the admin'),
    '#description' => t('Inidcates if the admin should be copied on warning e-mails'),
    '#default_value' => variable_get('user_warn_e-mail_bcc', FALSE),
  );


  return system_settings_form($form);
}

function user_warn_confirm_form($form, &$form_state, $uid) {
  $form['account'] = array(
    '#type' => 'value',
    '#value' => user_load($uid),
  );
  
  return confirm_form(
      $form, 
      t('Are you sure you want to send a waring email to this user?'),  
      'user' . $uid,
      t('This action cannot be undone'),
      t('Send E-mail'), 
      t('Cancel')
      );
}

function user_warn_confirm_form_submit($form, &$form_state) {
  $account = $form_state['values']['account'];
  
  drupal_mail(
      'user_warn', 
      'warn', 
      $account->mail, 
      user_preferred_language($account),
      $form_state['values'],
 variable_get('site_mail', NULL),
      TRUE
      );
}

/*
 * Implements hook_mail()
 */

function user_warn_mail($key, &$message, $params) {
  switch($key) {
    case 'warn' :
      $account = $params['account'];
      $subject = variable_get('user_warn_default_subject', 'Admisnistrative Warning');
      
      $body = variable_get('user_warn_e-mail_text', 'You\'ve Been Warned.');
      $admin_mail = variable_get('site_mail', NULL);
      
      if(variable_get('user_warn_e-mail_bcc', FALSE)) {
        
        $message['headers']['bcc'] = $admin_mail;
      }
      
      $message['to'] = $account->mail;
      $message['from'] = $admin_mail;
      $message['subject'] = $subject;
      $message['body'][] = token_replace($body, array('user' => $account));
      break;
  }
}